### Create a new favorite
POST http://localhost:3001/favorites/create
content-type: application/json

{ "title": "test", "movieId": 999, "releaseDate": "12-19-1996", "posterImage": "test", "description": "test", "averageRating": 4.4 }

### Get favorites
GET http://localhost:3001/favorites

### Delete a favorite
POST http://localhost:3001/favorites/delete/999